# Generated by Django 2.1.5 on 2019-01-07 18:53

from django.db import migrations, models
import django.db.models.deletion
import google_api.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=512, unique=True)),
                ('quota', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Google API',
            },
        ),
    ]
