# Generated by Django 2.1.5 on 2019-01-05 23:19

from django.db import migrations, models
import google_api.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteGoogle',
            fields=[
                ('nom', models.CharField(max_length=1024)),
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('credentials', google_api.fields.CredentialsField(null=True)),
            ],
        ),
    ]
