# Generated by Django 2.1.5 on 2019-01-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_message'),
        ('google_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(max_length=512, null=True)),
                ('erreur', models.TextField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.Contact')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.Message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_api.CompteGoogle')),
            ],
        ),
    ]
