# Generated by Django 2.1.5 on 2019-01-07 18:54

from django.db import migrations, models
import django.db.models.deletion
import google_api.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_contact'),
        ('google_api', '0001_googleapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sender.Contact')),
                ('user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('credentials', google_api.fields.CredentialsField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sender.contact',),
        ),
    ]
