# Generated by Django 2.1.5 on 2019-01-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0002_maillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=512, unique=True)),
                ('quota', models.BigIntegerField()),
            ],
        ),
    ]
