# Generated by Django 2.1.5 on 2019-01-07 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0003_googleapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='google_api.GoogleAPI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maillog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
