# Generated by Django 2.1.5 on 2019-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0004_googleapi_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleapi',
            name='quota',
            field=models.BigIntegerField(default=0),
        ),
    ]
