# Generated by Django 2.1.5 on 2019-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0004_abstractlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleapi',
            options={'verbose_name': 'Google API'},
        ),
        migrations.AddField(
            model_name='maillog',
            name='status',
            field=models.CharField(choices=[('S', 'Succès'), ('E', 'Erreur')], default='S', max_length=2),
            preserve_default=False,
        ),
    ]
