# Generated by Django 2.1.1 on 2018-10-04 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fichiers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='fichiers.Dossier')),
                ('proprietaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fichier', models.FileField(upload_to=fichiers.models.generate_filename)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='fichiers.Dossier')),
                ('proprietaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='fichier',
            unique_together={('nom', 'dossier')},
        ),
        migrations.AlterUniqueTogether(
            name='dossier',
            unique_together={('nom', 'parent')},
        ),
    ]
