# Generated by Django 2.1 on 2018-08-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uwsgi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vassal',
            options={'verbose_name_plural': 'vassaux'},
        ),
        migrations.RenameField(
            model_name='vassal',
            old_name='enabled',
            new_name='actif',
        ),
    ]
