# Generated by Django 2.1.4 on 2019-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ListeEnvoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1024)),
                ('contacts', models.ManyToManyField(to='sender.Contact')),
            ],
            options={
                'verbose_name': "liste d'envois",
                'verbose_name_plural': "listes d'envois",
            },
        ),
    ]
