# Generated by Django 2.1.5 on 2019-01-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Attente'), (2, 'Envoi en cours'), (3, 'Envoyé')], default=1)),
                ('objet', models.CharField(max_length=2048)),
                ('message', models.TextField()),
                ('clients', models.ManyToManyField(related_name='_message_clients_+', to='sender.Contact')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.Contact')),
            ],
        ),
    ]
