# Generated by Django 2.1.5 on 2019-01-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0001_initial'),
        ('sender', '0002_contact_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='google',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_api.CompteGoogle'),
        ),
    ]
