# Generated by Django 2.1.5 on 2019-01-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_sendqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeEnvoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1024)),
                ('contacts', models.ManyToManyField(to='sender.Contact')),
            ],
            options={
                'verbose_name': "liste d'envois",
                'verbose_name_plural': "listes d'envois",
            },
        ),
    ]
