# Generated by Django 2.1.5 on 2019-01-07 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_contact_compte_google'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=2048)),
                ('message', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sender.Contact')),
                ('clients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sender.ListeEnvoi')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.Contact')),
            ],
        ),
    ]
