# Generated by Django 2.1.5 on 2019-01-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_listeenvoi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendqueue',
            options={'verbose_name': "file d'envoi", 'verbose_name_plural': "file d'envoi"},
        ),
        migrations.AddField(
            model_name='contact',
            name='last_reset',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='per_query_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='quota',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='contact',
            name='reset_delta',
            field=models.DurationField(null=True),
        ),
    ]
