# Generated by Django 2.1.5 on 2019-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='client',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Attente'), (2, 'Envoi en cours'), (3, 'Envoyé')], default=1),
        ),
        migrations.RemoveField(
            model_name='message',
            name='clients',
        ),
        migrations.AddField(
            model_name='message',
            name='clients',
            field=models.ManyToManyField(related_name='_message_clients_+', to='sender.Contact'),
        ),
    ]
