# Generated by Django 2.1.5 on 2019-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_contact_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='max_quota',
            field=models.IntegerField(default=-1),
        ),
    ]
