# Generated by Django 2.1.5 on 2019-01-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_contact_max_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='quota',
            field=models.IntegerField(default=-1, help_text='valeur inférieure 0 pour quota infini'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reset_delta',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
