# Generated by Django 2.1.5 on 2019-01-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0008_polymorphic_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='clients',
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sender.Message')),
                ('clients', models.ManyToManyField(related_name='_mail_clients_+', to='sender.Contact')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sender.message',),
        ),
    ]
