# Generated by Django 2.1.5 on 2019-01-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0011_polymorphic_sendqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendQueueTemplate',
            fields=[
                ('sendqueue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sender.SendQueue')),
                ('clients', models.ManyToManyField(related_name='_sendqueuetemplate_clients_+', to='sender.Contact')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('sender.sendqueue',),
        ),
        migrations.AddField(
            model_name='template',
            name='messages_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
