# Generated by Django 2.1.1 on 2018-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwsgi_emperor', '0002_auto_20180820_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vassal',
            name='format',
            field=models.CharField(choices=[('.ini', 'INI'), ('.json', 'JSON'), ('.xml', 'XML'), ('.yaml', 'YAML')], max_length=5),
        ),
    ]
